# Generated by Django 3.2.23 on 2023-12-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sesseion_title', models.CharField(max_length=255)),
                ('chat_content', models.TextField()),
            ],
            options={
                'db_table': 'chat_session',
                'managed': False,
            },
        ),
    ]
