# Generated by Django 3.2.23 on 2023-12-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='session_id',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='session_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
