# Generated by Django 3.2.23 on 2023-12-27 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noticeboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comm_no', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=45)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('board_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='noticeboard.post')),
                ('user_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
