# Generated by Django 3.2.23 on 2023-12-29 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0003_post_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file',
        ),
        migrations.AddField(
            model_name='post',
            name='files',
            field=models.JSONField(default=list),
        ),
    ]
