# Generated by Django 3.2.23 on 2023-12-29 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0005_auto_20231229_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file',
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.FileField(upload_to='uploads/')),
                ('name', models.CharField(max_length=255)),
                ('board_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='noticeboard.post')),
            ],
        ),
    ]
