# Generated by Django 3.2.23 on 2023-12-29 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noticeboard', '0006_auto_20231229_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoticeFile',
            fields=[
                ('file_no', models.AutoField(primary_key=True, serialize=False)),
                ('src', models.FileField(upload_to='notice_uploads/')),
                ('name', models.CharField(max_length=255)),
                ('notice_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_files', to='noticeboard.notice')),
            ],
        ),
    ]
