# Generated by Django 3.2.23 on 2023-12-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0007_notice_noticefile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='user_no',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='notice_no',
        ),
        migrations.RemoveField(
            model_name='noticefile',
            name='file_no',
        ),
        migrations.AddField(
            model_name='notice',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticefile',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
