# Generated by Django 3.2.23 on 2023-12-30 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comm_Histroy',
            fields=[
                ('history_no', models.AutoField(db_column='history_no', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_column='title', max_length=255, null=True)),
                ('code', models.PositiveSmallIntegerField(blank=True, db_column='code', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_column='timestamp')),
                ('user_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Comm_Histroy',
                'managed': True,
            },
        ),
    ]
