# Generated by Django 3.2.23 on 2023-12-30 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_comm_histroy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comm_History_Sentence',
            fields=[
                ('sentence_no', models.AutoField(db_column='sentence_no', primary_key=True, serialize=False)),
                ('speaker', models.CharField(blank=True, db_column='speaker', max_length=32, null=True)),
                ('sentence', models.TextField(blank=True, db_column='sentence', null=True)),
                ('label_clear', models.PositiveSmallIntegerField(blank=True, db_column='label_clear', default=None, null=True)),
                ('label_concise', models.PositiveSmallIntegerField(blank=True, db_column='label_concise', default=None, null=True)),
                ('label_concrete', models.PositiveSmallIntegerField(blank=True, db_column='label_concrete', default=None, null=True)),
                ('label_correct', models.PositiveSmallIntegerField(blank=True, db_column='label_correct', default=None, null=True)),
                ('label_coherent', models.PositiveSmallIntegerField(blank=True, db_column='label_coherent', default=None, null=True)),
                ('label_complete', models.PositiveSmallIntegerField(blank=True, db_column='label_complete', default=None, null=True)),
                ('label_courteous', models.PositiveSmallIntegerField(blank=True, db_column='label_courteous', default=None, null=True)),
                ('timestamp', models.DateTimeField(blank=True, db_column='timestamp', null=True)),
                ('history_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learn.comm_histroy')),
            ],
            options={
                'db_table': 'Comm_History_Sentence',
                'managed': True,
            },
        ),
    ]
