# Generated by Django 3.2.23 on 2024-01-02 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_comm_history_sentence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comm_history_sentence',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='comm_histroy',
            options={'managed': False},
        ),
    ]
